import { streamText } from "ai";
import { initializeApp, cert, getApps } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import { NextResponse } from "next/server";
import { v4 as uuidv4 } from "uuid";
// Khởi tạo Firebase Admin nếu chưa có
if (!getApps().length) {
  initializeApp({
    credential: cert({
      projectId: "nongnghiepxanh-f6689",
      clientEmail: "firebase-adminsdk-fbsvc@nongnghiepxanh-f6689.iam.gserviceaccount.com",
      privateKey: `-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCR299QpFZJlkHL
FwFEs8uRkCkIWSUWpnbk9tyi+HVTMU9VfgW8tjXGO3n3KrlHqsHIAc9m5tPqM/OP
//6xwJWSShQbokNUO+utvJQyVb00h+nqTfOy9VhY8xq1g7HVbJ5RiHTuIggXb4gt
IbFkHi+hCGH0IkQxfaN2XUoO43l6oJY/vuVqPFZmluUe0gHF+OWkdD6omOin87oq
ujo/IqKurvtM6ooZcDEUIIdveIhLyCjfmDNoCTOiaFWUB3kjyDGNSdCIqASbE7zF
KSgOPx6lmAWd8r/RPImxJYMmlPb3nuG1cg53w2zxezNFFCUJ1zrIJgnMkIr24aaI
anINvqLxAgMBAAECggEAO3al/hxhSTLGs+M3EykxjrB06gBdzHQk+Idjv9UHD9mE
fFgaQqsOFTjeKlPyoTMOOVnzkgH81vhDDavRy+m1kKQ+ul1WkZq0JGpDCJpHvojC
ZlFNTuITGIBTnTiJYXccvCSjdwnMvrErlSqtRSHBTSc7t+nYX0zXPUQfEx7NwZ3k
uCEH/H7lJk4oD+O0iFmlnJinnTjtSkkWKT5sx31bT2aNLiyPXOJcShw5as2D9wp6
LoiPoQ5yyBUHIqzwQuiLRW39UsWpcAl5CTT0VjhsAktKoyJV9RF2G1ypK+21j0SX
J3vfoZPkJJGU4ZbIuwJxuEWtCWF65lVLXVsr819amQKBgQDImOjF2CueJgDiYupO
fFh4/oeyzaIShTSiFO96Ue24eDjJzmimkg7PlFS5kl3EZi5aZoX1rtChg0Wt92qN
0r92hpq9zVUIK3KeqBYNtLYRw9JbwrjLhZshn97lk8OgUD7/D3w0DQZUDTaYIiN6
QDy8wVTzhCtTc2R8GzmlRJQYcwKBgQC6JLimO/nmXcwV4KSbMvR5Y6fJfC2jV4Sf
ht4uTpK61ZMHO4joK+/KM7HJAW3Kp/fPHWNHxMaNRK1/vHYa3JdhCVD5nuo9DpQi
SNzHplCOJj+lngKU41TM4HDddSn5CFuM6WyAICkQm9ptsIU3bXS75b870C4jrn00
+qqvGNCSCwKBgQCoj0TaKuHMDKcllHTK6tX1JfylFQIhielGYU0yffHB1tPxUA7E
GWt0pnHjVciRJkPBFvFuFy2c6o/8tTDGZ9cXI9iXsRjIuqmgBCIz9iwgFWqITMG3
01ceFBba1yXFamjlLv/xRRiSPGApylYBfkULX3GhBujZQNepKb9wzoWbXQKBgH8J
hrd04UVWKG2Z5d1BtlWOLLm2tRLwLMQO8F1cJIm8Lt7Vw8boDXvLMf+DqSGQ5vAE
F3iok/VftKUjwtrsR6fjCs+BpE1NQM3xOjRLjlilQ/TM1Og2Ce7VElIhnyaljI2r
1O/QgxYht736pcBBRFTkJFI27vZNJIhettRPNDEnAoGAcX0H7IvZZuiXyadr6qDL
xtQUy1ZD5ip6MuHlwg/FLn28XsEcJkzZJCromdIHBQsSOcOBPTjwXl+1fc36Dw9t
qyVnSO/TpcpfChMqMtmRqvQPCQJjS/XjKsenvwm2LVm+wnGa6PNCAhCrBEUw8g1O
EY6K0KkW7YOS6h0mRhoMyPI=
-----END PRIVATE KEY-----`,
    }),
  });
}

const db = getFirestore();

export async function POST(req) {
  try {
    const seed = Math.floor(Math.random() * 100000);

    const prompt = `
Bạn là một chuyên gia viết nội dung về nông nghiệp. Mã ngữ cảnh: ${seed}

Hãy tự chọn một chủ đề bất kỳ liên quan đến nông nghiệp và viết một bài blog khoảng 800 từ.

Trước khi viết nội dung, hãy sinh ra các thông tin sau dưới dạng JSON (trừ category — sẽ được hệ thống gán sau):
{
  "title": "Tiêu đề bài viết",
  "author": "Tên tác giả (có thể là bút danh)",
  "tags": ["Từ khóa liên quan"],
  "tone": "Giọng văn phù hợp",
  "style": "Cách trình bày bài viết"
}

Sau đó, viết nội dung bài blog theo phong cách bạn thấy phù hợp với chủ đề đã chọn.
`;

    const result = await streamText({
      model: "openai/o4-mini",
      prompt,
    });

    let fullText = "";
    for await (const chunk of result.textStream) {
      fullText += typeof chunk === "string"
        ? chunk
        : new TextDecoder().decode(chunk);
    }

    // Tách phần JSON metadata
    const jsonStart = fullText.indexOf("{");
    const jsonEnd = fullText.indexOf("}") + 1;
    const metadataText = fullText.slice(jsonStart, jsonEnd);
    const metadata = JSON.parse(metadataText);

    // Tách nội dung bài viết
    const content = fullText.slice(jsonEnd).trim();

    // Danh sách chuyên mục cố định
    const categories = [
      { value: "cay-trong", label: "🌾 Cây trồng" },
      { value: "sau-benh", label: "🐛 Sâu bệnh" },
      { value: "dat-dai", label: "🌍 Đất đai" },
      { value: "ky-thuat", label: "⚙️ Kỹ thuật" },
    ];

    // Gán ngẫu nhiên một category từ danh sách
    const randomCategory = categories[Math.floor(Math.random() * categories.length)];
    metadata.category = randomCategory.value;
    metadata.categoryLabel = randomCategory.label;

    // Ghi vào Firestore
    await db.collection("articles").add({
      id: uuidv4(),
      ...metadata,
      content,
      seed,
      date: new Date(),
      views: 0,
      autoGenerated: true
    });

    // Trả về response không cache
    return new Response(JSON.stringify({
      message: "✅ Bài viết mới đã được tạo",
      metadata,
      content
    }), {
      headers: {
        "Content-Type": "application/json",
        "Cache-Control": "no-store"
      }
    });
  } catch (error) {
    console.error("❌ Lỗi tạo bài viết:", error);
    return new Response(JSON.stringify({
      error: "Lỗi khi tạo bài viết",
      details: error.message
    }), {
      status: 500,
      headers: {
        "Content-Type": "application/json",
        "Cache-Control": "no-store"
      }
    });
  }
}